baseURL = "https://poemgreen.xyz"
languageCode = "zh-cn"
defaultContentLanguage = "zh"
title = "绿 松 石"
disableKinds = ["section"]
disqusShortname = ""
pygmentsCodeFences = false
pygmentsUseClasses = false
paginate = 9999
minify = true
disableHugoGeneratorInject = false

[params.robots]
  noindex = true
  nofollow = true

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true

[params]
  description = "My private collection of poems by other authors"
  author = "bernardlaloe74@gmail.com"
  copyright = ""
  logo = ""

[frontmatter]
  date  = [":filename", ":default"]
  author = "bernardlaloe74@gmail.com"
  github = ""
  facebook = ""
  og_image = ""
  sitename = "绿 松 石"
  twitter = ""

[permalinks]
  posts = "/:year/:month/:day/:filename"
  pages = "/:slug"
  photos = "/:year/:month/:day/:filename"

[outputs]
  home = ["HTML"]
  section = ["HTML"]

[menu]
  [[menu.main]]
    identifier = "index"
    name       = "Index"
    url        = "/"
    weight     = -111

  [[menu.main]]
    identifier = "views"
    name       = "Views"
    url        = "/views/"
    weight     = -30

  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about/"
    weight     = -20

